services:
  backend:
    image: ibrahimyemi/blog-backend:latest
    container_name: blog_backend
    entrypoint: entrypoint-app.sh
    env_file:
      - ./backend/.env
    expose:
      - "9000"
    volumes:
      - storage_data:/var/www/storage
    depends_on:
      - mysql
      - redis
    networks:
      - app

  nginx:
    image: nginx:alpine
    container_name: blog_nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - storage_data:/var/www/storage:ro
    depends_on:
      - backend
    networks:
      - app

  mysql:
    image: mysql:8
    container_name: blog_mysql
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app

  redis:
    image: redis:alpine
    container_name: blog_redis
    networks:
      - app

  horizon:
    image: ibrahimyemi/blog-backend:latest
    container_name: blog_horizon
    entrypoint: entrypoint-worker.sh
    command: php artisan horizon
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - mysql
    networks:
      - app

  scheduler:
    image: ibrahimyemi/blog-backend:latest
    container_name: blog_scheduler
    entrypoint: entrypoint-worker.sh
    command: php artisan schedule:work
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
      - redis
    networks:
      - app

  frontend:
    image: ibrahimyemi/blog-frontend:latest
    container_name: blog_frontend
    ports:
      - "3000:80"
    networks:
      - app

networks:
  app:

volumes:
  mysql_data:
  storage_data:
