services:
  backend-test:
    entrypoint: ["sh", "-c", "sleep infinity"]
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    env_file:
      - ./backend/.env.testing
    depends_on:
      - mysql-test
      - redis-test
    networks:
      - test-network

  mysql-test:
    image: mysql:8
    environment:
      MYSQL_DATABASE: testing
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - test-network

  redis-test:
    image: redis:alpine
    networks:
      - test-network

networks:
  test-network: